### ISSUE TITLE
Timeframe

### ISSUE THREAD

**Issue by Dreamer2345** [Dreamer2345/Forge-Level-Editor#56]
Ok as this tool looks almost complete I wanted to ask if I should turn this repo public now, or wait until the publishment of the game and then set it to public? Honestly Ive no clue myself.

**Comment by Dreamer2345** [comment]
Repostitory has been set to public

**Comment by Pharap** [comment]
It's just occurred to me that the problem with forking it is that any future changes would then have to be made on the fork, so at some point we'd have to stop making issues and PRs on this repo and switch to the forked repo instead, otherwise the fork has to be continually updated.

I.e. desynchronisation issues.
